services:
  application:
    image: ${APP_NAME}-php
    build:
      context: ./docker/php/${PHP_VERSION}
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
        - ${APP_ROOT_DIR}:/var/www
    networks:
      default: null
  nginx:
    image: nginx:1.23-alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_ROOT_DIR}:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      default: null
  database:
    image: mysql:8.0-oracle
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      default: null

networks:
  default:
    name: ${APP_NAME}-network
